### ISSUE TITLE
What are we doing with this contexts list?

### ISSUE THREAD

**Issue by kevinscaria** [kevinscaria/PolyMATH#27]
@ujjwalaananth 

https://github.com/kevinscaria/PolyMATH/blob/6c8a625ff67557701a1c4af591211ae872980dad/scripts/annotation_utils.py#L31

```

# Extract all screenshots into respective lists
    files = [os.path.basename(p) for p in glob.glob(os.path.join(paper_path, qdir,'*.png'))]
    contexts = [os.path.basename(p) for p in glob.glob(os.path.join(paper_path, cdir,'*.png')) \
                if os.path.basename(p)[0]=='c']
    questions = pd.Series([p.split('_')[0] for p in files if p[0]=='q']).unique()  
```

**Comment by kevinscaria** [comment]
Looks like it is getting overridden in line 39. So what is the point of the iteration in line 31

**Comment by ujjwalaananth** [comment]
good catch - 31 is unnecessary since we add more flexible logic in lines 57-60. this can be dropped.

**Comment by kevinscaria** [comment]
Perfect. Will revise it in next revision
